modLoader="javafml"
loaderVersion="[34,)"
license="GNU LGPL 3.0"
issueTrackerURL="https://github.com/CodersLabs/Tougher-Glass-Forge/issues"
[[mods]]
modId="tougherglass"
version="1.1.0"
displayName="Tougher Glass"
logoFile="tougherglass.png"
credits="justinplayz91, EltrutLikes"
authors="CodersLabs"
description='''
'''

[[dependencies.tougherglass]]
    modId="forge"
    mandatory=true
    versionRange="[34,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.tougherglass]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3, 1.17)"
    ordering="NONE"
    side="BOTH"
	
[[dependencies.tougherglass]]
    modId="differentiate"
    mandatory=true
    versionRange="[0.3.2,)"
    ordering="AFTER"
    side="BOTH"