modLoader="javafml"
loaderVersion="[41,)"
license="GNU LGPL 3.0"
issueTrackerURL="https://github.com/CodersLabs/Tougher-Glass-Forge/issues"
[[mods]]
modId="tougherglass"
version="${file.jarVersion}"
displayName="Tougher Glass"
logoFile="tougherglass.png"
credits="justinplayz91, EltrutLikes, Uraneptus"
authors="CodersLabs"
description='''
'''

[[dependencies.tougherglass]]
    modId="forge"
    mandatory=true
    versionRange="[41.1,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.tougherglass]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,)"
    ordering="NONE"
    side="BOTH"
	
[[dependencies.tougherglass]]
    modId="blueprint"
    mandatory=true
    versionRange="[6.0.5,)"
    ordering="AFTER"
    side="BOTH"