modLoader="javafml"
loaderVersion="[37,)"
license="GNU LGPL 3.0"
issueTrackerURL="https://github.com/CodersLabs/Tougher-Glass-Forge/issues"
[[mods]]
modId="tougherglass"
version="1.0.0"
displayName="Tougher Glass"
logoFile="tougherglass.png"
credits="justinplayz91, EltrutLikes, Uraneptus"
authors="CodersLabs"
description='''
'''

[[dependencies.tougherglass]]
    modId="forge"
    mandatory=true
    versionRange="[37,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.tougherglass]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17.1,)"
    ordering="NONE"
    side="BOTH"
	
[[dependencies.tougherglass]]
    modId="differentiate"
    mandatory=true
    versionRange="[0.5.3,)"
    ordering="AFTER"
    side="BOTH"